name: monai
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.4.1
      - beautifulsoup4==4.12.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - comm==0.2.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - filelock==3.13.1
      - fonttools==4.49.0
      - fsspec==2024.2.0
      - gdown==5.1.0
      - idna==3.6
      - importlib-metadata==7.0.1
      - importlib-resources==6.1.1
      - ipykernel==6.29.2
      - ipython==8.18.1
      - jedi==0.19.1
      - jinja2==3.1.3
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - monai==1.3.0
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - packaging==23.2
      - pandas==2.2.0
      - parso==0.8.3
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.2.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==15.0.0
      - pygments==2.17.2
      - pyparsing==3.1.1
      - pysocks==1.7.1
      - python-dateutil==2.8.2
      - pytz==2024.1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - requests==2.31.0
      - simpleitk==2.3.1
      - six==1.16.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - sympy==1.12
      - torch==2.2.0
      - torchviz==0.0.2
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.1
      - triton==2.2.0
      - typing-extensions==4.9.0
      - tzdata==2024.1
      - urllib3==2.2.0
      - wcwidth==0.2.13
      - zipp==3.17.0
